# Generated by Django 6.1.1 on 2026-09-13 11:35

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this department from new employee forms, without deleting past records that use it.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this designation from new employee forms, without deleting past records that use it.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text="Your office's existing employee code. Must be unique.", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-/]+$', 'Employee ID can only contain letters, numbers, hyphens, and slashes.')])),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('date_joined', models.DateField()),
                ('employment_type', models.CharField(choices=[('REGULAR', 'Regular'), ('CONTRACT', 'Contract'), ('HKRNL', 'HKRNL'), ('DEPUTATION', 'Deputation'), ('GUEST_FACULTY', 'Guest Faculty'), ('OTHER', 'Other')], default='REGULAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='people.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='people.designation')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text="Your office's existing employee code. Must be unique.", max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-/]+$', 'Employee ID can only contain letters, numbers, hyphens, and slashes.')])),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('date_joined', models.DateField()),
                ('employment_type', models.CharField(choices=[('REGULAR', 'Regular'), ('CONTRACT', 'Contract'), ('HKRNL', 'HKRNL'), ('DEPUTATION', 'Deputation'), ('GUEST_FACULTY', 'Guest Faculty'), ('OTHER', 'Other')], default='REGULAR', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.department')),
                ('designation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.designation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
