# Generated by Django 6.1.1 on 2026-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_assign_contactdetails_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initials',
            field=models.CharField(blank=True, choices=[('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='initials',
            field=models.CharField(blank=True, choices=[('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=10),
        ),
    ]
