# Generated by Django 6.1.1 on 2026-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_employee_initials_historicalemployee_initials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='initials',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(choices=[('TEACHING', 'Teaching'), ('WORKSHOP', 'Workshop'), ('ADMINISTRATIVE', 'Administrative'), ('OTHER', 'Other')], default='OTHER', help_text='Broad category of role — separate from Employment Type.', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='initial',
            field=models.CharField(blank=True, choices=[('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('SHRI', 'Shri'), ('SMT', 'Smt.')], default='', help_text='Title/Salutation (optional).', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='employee_category',
            field=models.CharField(choices=[('TEACHING', 'Teaching'), ('WORKSHOP', 'Workshop'), ('ADMINISTRATIVE', 'Administrative'), ('OTHER', 'Other')], default='OTHER', help_text='Broad category of role — separate from Employment Type.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='initial',
            field=models.CharField(blank=True, choices=[('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('SHRI', 'Shri'), ('SMT', 'Smt.')], default='', help_text='Title/Salutation (optional).', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(blank=True, help_text='Optional for now — can be filled in later.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='date_joined',
            field=models.DateField(blank=True, help_text='Optional for now — can be filled in later.', null=True),
        ),
    ]
